require 'dotenv/load'  # loads .env if you use it

default_platform(:android)

platform :android do
  desc "Build Android and upload to Firebase"
  lane :firebase_android do
      
    apk = File.expand_path("../#{ENV["ANDROID_FILE_PATH"]}", __dir__)
    UI.message("Resolved APK absolute path: #{apk}")
    
    unless File.exist?(apk)
      UI.user_error!("APK not found at path: #{apk}")
    end

    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      apk_path: apk,
      groups: "internal-testers",
      release_notes: "Automated build"
    )
  end

  desc "Build iOS and upload to Firebase"
  lane :firebase_ios do
    sh("eas build --platform ios --profile preview --non-interactive")

    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      groups: "testers",
      release_notes: "Expo CI iOS Beta"
    )
  end

  # placeholders for future App Store / Play Store release
  lane :release_ios do
    UI.message("App Store release placeholder. Add Apple credentials later.")
  end

  lane :release_android do
    UI.message("Play Store release placeholder. Add Google credentials later.")
  end
end
