require 'dotenv/load'  # loads .env if you use it

default_platform(:expo)

platform :expo do
  desc "Build Android and upload to Firebase"
  lane :firebase_android do

    apk_path = ENV["ANDROID_FILE_PATH"]

    unless File.exist?(apk_path)
      UI.user_error!("APK not found at path: #{apk_path}")
    end

    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      file: apk_path,
      groups: "testers",
      release_notes: "Expo CI Android Beta"
    )
  end

  desc "Build iOS and upload to Firebase"
  lane :firebase_ios do
    sh("eas build --platform ios --profile preview --non-interactive")

    firebase_app_distribution(
      app: ENV["FIREBASE_IOS_APP_ID"],
      groups: "testers",
      release_notes: "Expo CI iOS Beta"
    )
  end

  # placeholders for future App Store / Play Store release
  lane :release_ios do
    UI.message("App Store release placeholder. Add Apple credentials later.")
  end

  lane :release_android do
    UI.message("Play Store release placeholder. Add Google credentials later.")
  end
end
